### ISSUE TITLE
Create prisma schema and integrate to MongoDB

### ISSUE THREAD

**Issue by Jbnado** [rp-js/rpjs-website#3]
Create schema and relationships using prisma and then integrate to our MongoDB.

Follow this schema:
![untitled](https://github.com/rp-js/rpjs-website/assets/73846881/171ceb57-d27e-4bd7-9669-fe848c39f5f6)

We can discuss about the table relations and its attributes, but since we're working with a NoSQL database this is easy to manipulate and change.

**Comment by PedroLuisBrilhadori** [comment]
I think we can:
- add created_at to the entities like Users, Speakers, Events and Subscriptions;
- add phone_number in Users entity.

**Comment by Jbnado** [comment]
Yeah, sure, but created_at and updated_at are automatically created by mongo, right? And phone_number is a great idea.

**Comment by PedroLuisBrilhadori** [comment]
even if Mongodb creates these tables, I think the diagram must have these columns. We don't need to know Mongodb to understand the diagram. 

And this can cause a problem, example: 
if we change database and it doesn't have created_at the diagram would remember. 

In primsa schema these columns are unless, but in the diagram they are cool, right?

**Comment by Jbnado** [comment]
You're right, and I think in prisma schema we need to write this.
